import type { Metadata } from 'next';
import './globals.css';
import Image from "next/image"
import { Sidebar } from '@/components/sidebar';
import { Poppins } from 'next/font/google';
import { SessionProvider } from 'next-auth/react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={poppins.variable}>
      <body className="antialiased relative ">


        {/* Sidebar fixa no topo */}
        <Sidebar />

        {/* Conteúdo principal */}
        <main className='relative z-10 w-full flex flex-col items-center'>
          {/* Vou manter o código da marca d'água comentado, caso seja necessário retornar */}
          {/* <div style={{
            zIndex: -1,
            position: 'fixed',
            width: "100vw",
            height: "100vh",
            top: 55,
            left: 0,
            opacity: 0.04

          }}>
            <Image src={"/Brasao.png"} alt={"Brasao da turma"}
              layout='fill'
              objectFit='contain' />
          </div> */}
          <SessionProvider>{children}</SessionProvider>
        </main>

      </body>
    </html>
  );
}
